function selectionGui

global meta  
global state 
global data  

global gh

gh.userFigure = figure(101);
set(gcf,'units','normalized','outerposition',[0 0 1 0.2662]);

% Setup epoch selection
gh.epoch = 1;
uicontrol('Style','popup',...
    'units','normalized','Position', [0.03 0.65 0.15 0.25],...
    'Fontsize',16,...
    'String',cellfun(@(e) sprintf('Epoch %d', e), num2cell(1:meta.NE),'uni',0),...
    'callback',@setDataType);

% Setup individual trials selector 
uicontrol('Style', 'checkbox',... 
    'String', {'Phys Traces OK'},'Fontsize',16,...
    'units','normalized','Position', [0.03 0.4 0.15 0.25],...
    'Callback', @setPhysTraces);
global physokay  
physokay = 1;   

% Setup individual trials selector 
uicontrol('Style', 'checkbox',...
    'String', {'Imag Traces OK'},'Fontsize',16,...
    'units','normalized','Position', [0.03 0.15 0.15 0.25],...
    'Callback', @setImagTraces);
global imagokay
imagokay = 1;

% Setup data type selection
global dataType
dataType = 1;
uicontrol('Style','popup',...
    'units','normalized','Position', [0.2 0.65 0.15 0.25],...
    'Fontsize',16,...
    'String',{'no selection','baseline','injection','ap','uncage','interaction','omit'},...
    'callback',@setDataType);

% Setup analysis options
% global anOptions
uicontrol('Style','popup',...
    'units','normalized','Position', [0.2 0.36 0.15 0.25],...
    'Fontsize',16,...
    'String',{'options','analysisTypes...'},...
    'callback',@setDataType);

% Setup continue button
uicontrol('Style', 'checkbox',...
    'String', {'continue...'},'Fontsize',16,...
    'units','normalized','Position', [0.2 0.15 0.15 0.25],...
    'Callback', @completeGui);
global cGui
cGui = 0;


